export const messages = {
  zh: {
    previewTemplate: "预览", templatePreviewTitle: "预览 · {name}", useTemplate: "使用此模板", backToTemplates: "返回模板库", templatePreviewHint: "可直接体验交互，使用模板后编辑代码。",
    resizeConsole: "调整控制台高度", resizeConsoleHint: "上下拖动调整高度，双击恢复默认；也可使用上下方向键",
    templates: "模板库", templatesHint: "选择一个起点，创建属于你的新项目。", close: "关闭", searchProjects: "搜索项目名称或代码", noProjects: "没有找到匹配的项目", workspaceTools: "创作工作台", layout: "布局", sideLayout: "左右分栏", stackedLayout: "上下分栏", resizePanels: "调整编辑区和预览区大小", undo: "撤销", redo: "重做", findReplace: "查找 / 替换", format: "格式化", formatFailed: "无法格式化，请检查代码语法。", formatCancelled: "代码已改变，本次格式化未覆盖新内容。", custom: "自定义", width: "宽", height: "高", rotate: "旋转", console: "控制台", consoleLevel: "级别", allLogs: "全部", normalLogs: "日志", warnings: "警告", errors: "错误", preserveLogs: "保留日志", clear: "清空", collapse: "收起", noLogs: "暂无日志，试试 console.log('Hello')。", consoleNewRun: "── 新一次运行 ──", dayMode: "日间模式", nightMode: "夜间模式",
    workspaceFullscreen: "工作台全屏", previewFullscreen: "全屏预览", exitFullscreen: "退出全屏", enterFullscreenHint: "进入全屏，按 Esc 可退出", exitFullscreenHint: "退出全屏（Esc）", fullscreenUnavailable: "当前浏览器或嵌入窗口不支持全屏，请在 Chrome 或 Edge 标签页中打开。", fullscreenFailed: "全屏切换失败，请重试。",
    brandSub: "你的网页实验室", projects: "我的项目", newProject: "新建项目", localOnly: "保存在这台浏览器", backupHint: "导出一份备份，把灵感带到别处。", import: "导入 JSON", export: "导出全部", workspace: "工作空间", rename: "重命名", delete: "删除", run: "运行预览", preview: "实时预览", desktop: "桌面", mobile: "手机", autoRun: "自动运行", runtimeError: "JavaScript 错误", tip: "小提示：完整 HTML 也可以直接粘贴，样式与脚本会一起运行。", footer: "一点代码，一点可能。", projectName: "项目名称", cancel: "取消", confirm: "确定", saved: "已保存到本地", saveFailed: "保存失败，请导出备份", loadFailed: "本地数据暂时无法读取，原始数据已保留。当前修改无法保存，请导出备份。", exampleName: "第一颗灵感", untitled: "未命名项目", lines: "行", chars: "字符", running: "正在渲染…", rendered: "预览已更新", previewFailed: "预览未响应，请重新运行", pending: "代码已修改，待运行", imported: "已导入 {count} 个项目副本", exported: "已导出全部项目", importFailed: "导入失败：请选择有效的 Web Renderer JSON 备份。", tooLarge: "文件过大，请使用 4 MB 以内的 JSON 备份。", projectLimit: "最多支持 100 个项目，请先导出并清理。", confirmDelete: "删除「{name}」？此操作无法撤销，建议先导出备份。", deleted: "项目已删除", synced: "已同步其他标签页的修改", emptyName: "请输入项目名称。", exportFailed: "导出失败，请重试。", previewTitle: "网页预览", errorStatus: "发现脚本错误", backupTooLarge: "数据超过 4 MB，请拆分项目后再保存。"
  },
  en: {
    previewTemplate: "Preview", templatePreviewTitle: "Preview · {name}", useTemplate: "Use template", backToTemplates: "Back to templates", templatePreviewHint: "Try the interactions, then use the template to edit its code.",
    resizeConsole: "Resize console height", resizeConsoleHint: "Drag vertically to resize; double-click to reset. Arrow keys also work.",
    templates: "Templates", templatesHint: "Pick a starting point and create a new project.", close: "Close", searchProjects: "Search projects or code", noProjects: "No matching projects", workspaceTools: "CREATIVE WORKSPACE", layout: "Layout", sideLayout: "Side by side", stackedLayout: "Stacked", resizePanels: "Resize editor and preview", undo: "Undo", redo: "Redo", findReplace: "Find / replace", format: "Format", formatFailed: "Cannot format. Check the code syntax.", formatCancelled: "The code changed; formatting was not applied.", custom: "Custom", width: "W", height: "H", rotate: "Rotate", console: "Console", consoleLevel: "Level", allLogs: "All", normalLogs: "Logs", warnings: "Warnings", errors: "Errors", preserveLogs: "Preserve", clear: "Clear", collapse: "Hide", noLogs: "No logs yet. Try console.log('Hello').", consoleNewRun: "── New run ──", dayMode: "Light mode", nightMode: "Dark mode",
    workspaceFullscreen: "Fullscreen", previewFullscreen: "Full preview", exitFullscreen: "Exit fullscreen", enterFullscreenHint: "Enter fullscreen; press Esc to exit", exitFullscreenHint: "Exit fullscreen (Esc)", fullscreenUnavailable: "Fullscreen is unavailable here. Open this page in a Chrome or Edge tab.", fullscreenFailed: "Could not change fullscreen mode. Please try again.",
    brandSub: "A playground for your ideas", projects: "MY PROJECTS", newProject: "New project", localOnly: "Saved in this browser", backupHint: "Export a backup. Take your ideas anywhere.", import: "Import JSON", export: "Export all", workspace: "Workspace", rename: "Rename", delete: "Delete", run: "Run preview", preview: "Live preview", desktop: "Desktop", mobile: "Mobile", autoRun: "Auto-run", runtimeError: "JavaScript error", tip: "Tip: Paste a full HTML document, including its styles and scripts.", footer: "Small code. New possibilities.", projectName: "Project name", cancel: "Cancel", confirm: "Confirm", saved: "Saved locally", saveFailed: "Save failed. Export a backup.", loadFailed: "Local data could not be read and was left untouched. Changes cannot be saved; export a backup.", exampleName: "A little inspiration", untitled: "Untitled project", lines: "lines", chars: "chars", running: "Rendering…", rendered: "Preview updated", previewFailed: "Preview did not respond. Run again.", pending: "Changes waiting to run", imported: "Imported {count} project copies", exported: "All projects exported", importFailed: "Import failed. Choose a valid Web Renderer JSON backup.", tooLarge: "Choose a JSON backup smaller than 4 MB.", projectLimit: "Up to 100 projects. Export and remove some first.", confirmDelete: 'Delete “{name}”? This cannot be undone. Export a backup first if needed.', deleted: "Project deleted", synced: "Synced changes from another tab", emptyName: "Enter a project name.", exportFailed: "Export failed. Please try again.", previewTitle: "Web preview", errorStatus: "Script error detected", backupTooLarge: "Data exceeds 4 MB. Split projects before saving."
  }
};
